/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-tier.cjs

import { lazy } from 'react';
import type { ComponentType, LazyExoticComponent } from 'react';

type MaybeLazyPage = LazyExoticComponent<ComponentType<any>> | null;

export const Actuals: MaybeLazyPage = lazy(() => import('@pages/data/Actuals'));
export const DataImport: MaybeLazyPage = lazy(() => import('@pages/data/DataImport'));
export const Dimensions: MaybeLazyPage = lazy(() => import('@pages/data/Dimensions'));
export const ProductMaster: MaybeLazyPage = lazy(() => import('@pages/data/ProductMaster'));
export const Locations: MaybeLazyPage = lazy(() => import('@pages/data/Locations'));
export const ForecastDashboard: MaybeLazyPage = lazy(() => import('@pages/forecasts/ForecastDashboard'));
export const ForecastDetail: MaybeLazyPage = lazy(() => import('@pages/forecasts/ForecastDetail'));
export const Forecasts: MaybeLazyPage = lazy(() => import('@pages/forecasts/Forecasts'));
export const ManufacturingRoutes: MaybeLazyPage = lazy(() => import('@pages/manufacturing/ManufacturingRoutes'));
export const CreatePlan: MaybeLazyPage = lazy(() => import('@pages/plans/CreatePlan'));
export const PlanDetail: MaybeLazyPage = lazy(() => import('@pages/plans/PlanDetail'));
export const Plans: MaybeLazyPage = lazy(() => import('@pages/plans/Plans'));
export const Reports: MaybeLazyPage = lazy(() => import('@pages/reports/Reports'));
export const Scenarios: MaybeLazyPage = lazy(() => import('@pages/scenarios/Scenarios'));
export const AuditLog: MaybeLazyPage = lazy(() => import('@pages/settings/AuditLog'));
export const Notifications: MaybeLazyPage = lazy(() => import('@pages/settings/Notifications'));
export const MargEde: MaybeLazyPage = lazy(() => import('@pages/settings/MargEde'));
export const Users: MaybeLazyPage = lazy(() => import('@pages/settings/Users'));
