/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-tier.cjs

type Loader = () => Promise<unknown>;

export const BUILD_DASHBOARD_PREFETCH_LOADERS: Loader[] = [
  () => import('@pages/Dashboard'),
  () => import('@pages/forecasts/Forecasts'),
  () => import('@pages/plans/Plans'),
  () => import('@pages/manufacturing/ManufacturingRoutes'),
  () => import('@pages/manufacturing/ManufacturingDashboard'),
];
export const BUILD_PLANS_PREFETCH_LOADERS: Loader[] | null = [
  () => import('@pages/plans/Plans'),
  () => import('@pages/plans/PlanDetail'),
  () => import('@pages/plans/CreatePlan'),
];
export const BUILD_FORECASTS_PREFETCH_LOADERS: Loader[] | null = [
  () => import('@pages/forecasts/Forecasts'),
  () => import('@pages/forecasts/ForecastDetail'),
];
export const BUILD_SCENARIOS_PREFETCH_LOADERS: Loader[] | null = [
  () => import('@pages/scenarios/Scenarios'),
];
export const BUILD_DATA_PREFETCH_LOADERS: Loader[] | null = [
  () => import('@pages/data/DataImport'),
  () => import('@pages/data/Actuals'),
  () => import('@pages/data/ProductMaster'),
  () => import('@pages/data/Dimensions'),
];
export const BUILD_REPORTS_PREFETCH_LOADERS: Loader[] | null = [
  () => import('@pages/reports/Reports'),
];
export const BUILD_SETTINGS_PREFETCH_LOADERS: Loader[] = [
  () => import('@pages/settings/Settings'),
  () => import('@pages/settings/Profile'),
  () => import('@pages/settings/Users'),
  () => import('@pages/settings/MargEde'),
  () => import('@pages/settings/AuditLog'),
  () => import('@pages/settings/Notifications'),
];
export const BUILD_MANUFACTURING_PREFETCH_LOADERS: Loader[] | null = [
  () => import('@pages/manufacturing/ManufacturingRoutes'),
  () => import('@pages/manufacturing/ManufacturingDashboard'),
  () => import('@pages/manufacturing/BOM'),
  () => import('@pages/manufacturing/MRP'),
  () => import('@pages/manufacturing/WorkOrders'),
  () => import('@pages/manufacturing/Inventory'),
  () => import('@pages/manufacturing/Production'),
];
