/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-tier.cjs

export type BuildTier = 'basic' | 'growth' | 'enterprise';

export const BUILD_TIER: BuildTier = 'enterprise';

export const BUILD_TIER_MODULES = {
  planning: true,
  forecasting: true,
  data: true,
  reports: true,
  manufacturing: true,
  users: true,
  audit: true,
  notifications: true,
  integrations: true,
} as const;

export type BuildTierModuleKey = keyof typeof BUILD_TIER_MODULES;

export const BUILD_HAS_PLANNING = true as const;
export const BUILD_HAS_FORECASTING = true as const;
export const BUILD_HAS_DATA = true as const;
export const BUILD_HAS_REPORTS = true as const;
export const BUILD_HAS_MANUFACTURING = true as const;
export const BUILD_HAS_USERS = true as const;
export const BUILD_HAS_AUDIT = true as const;
export const BUILD_HAS_NOTIFICATIONS = true as const;
export const BUILD_HAS_INTEGRATIONS = true as const;
