/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-tier.cjs

import { AuthModule } from '../../modules/auth/auth.module';
import { UsersModule } from '../../modules/users/users.module';
import { PlansModule } from '../../modules/plans/plans.module';
import { ForecastsModule } from '../../modules/forecasts/forecasts.module';
import { ScenariosModule } from '../../modules/scenarios/scenarios.module';
import { DataModule } from '../../modules/data/data.module';
import { SettingsModule } from '../../modules/settings/settings.module';
import { ReportsModule } from '../../modules/reports/reports.module';
import { ManufacturingModule } from '../../modules/manufacturing/manufacturing.module';
import { AuditFeatureModule } from '../../modules/audit/audit.module';
import { NotificationFeatureModule } from '../../modules/notifications/notification.module';
import { MargEdeModule } from '../../modules/marg-ede/marg-ede.module';

export type BuildTier = 'basic' | 'growth' | 'enterprise';

export const BUILD_TIER: BuildTier = 'enterprise';

export const BUILD_TIER_MODULES = {
  planning: true,
  forecasting: true,
  data: true,
  reports: true,
  manufacturing: true,
  users: true,
  audit: true,
  notifications: true,
  integrations: true,
} as const;

export const BUILD_TIER_FEATURE_MODULE_IMPORTS = [
  AuthModule,
  UsersModule,
  PlansModule,
  ForecastsModule,
  ScenariosModule,
  DataModule,
  SettingsModule,
  ReportsModule,
  ManufacturingModule,
  AuditFeatureModule,
  NotificationFeatureModule,
  MargEdeModule,
] as const;
